<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="@yield('meta_description', config('app.name') . ' — Logiciel de facturation et gestion commerciale en ligne')">
		<meta name="author" content="{{ config('app.name', 'Hssabek') }}">
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<title>@yield('title', 'Accueil') | {{ config('app.name', 'Hssabek') }}</title>

		<!-- Favicons (generated by realfavicongenerator) -->
		<link rel="icon" type="image/png" href="/assets/images/favicon/favicon-96x96.png" sizes="96x96" />
		<link rel="icon" type="image/svg+xml" href="/assets/images/favicon/favicon.svg" />
		<link rel="shortcut icon" href="/assets/images/favicon/favicon.ico" />
		<link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.png" />
		<meta name="apple-mobile-web-app-title" content="Hssabek" />
		<link rel="manifest" href="/assets/images/favicon/site.webmanifest" />

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url('build/css/bootstrap.min.css') }}">

		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{{ url('build/plugins/fontawesome/css/fontawesome.min.css') }}">
		<link rel="stylesheet" href="{{ url('build/plugins/fontawesome/css/all.min.css') }}">

		<!-- Aos CSS -->
		<link rel="stylesheet" href="{{ url('build/plugins/aos/aos.css') }}">

		<!-- Owl carousel CSS -->
		<link rel="stylesheet" href="{{ url('build/css/owl.carousel.min.css') }}">

		<!-- Feather CSS -->
		<link rel="stylesheet" href="{{ url('build/css/feather.css') }}">

		<!-- Iconsax CSS -->
		<link rel="stylesheet" href="{{ url('build/css/iconsax.css') }}">

		<!-- Landing CSS -->
		<link rel="stylesheet" href="{{ url('build/css/landing.css') }}">

		@stack('styles')
	</head>

<body>

	<div class="main-wrapper">

		@hasSection('hero')
		<div class="main-banner">
			@include('frontoffice.components.navbar')
			@yield('hero')
		</div>
		@else
			@include('frontoffice.components.navbar')
		@endif

		<div data-bs-spy="scroll" data-bs-target="#scroll-nav" class="scrollspy-example" tabindex="0">
			@yield('content')
			@include('frontoffice.components.footer')
		</div>

		<div class="mouse-cursor cursor-outer"></div>
		<div class="mouse-cursor cursor-inner"></div>

		<div class="back-to-top">
			<a class="back-to-top-icon align-items-center justify-content-center d-flex" href="#top"><i class="fa fa-chevron-up" aria-hidden="true"></i></a>
		</div>
	</div>

	<!-- jQuery -->
	<script src="{{ url('build/js/jquery-3.7.1.min.js') }}"></script>

	<!-- Bootstrap Core JS -->
	<script src="{{ url('build/js/bootstrap.bundle.min.js') }}"></script>
	<script src="{{ url('build/js/bootstrap-scrollspy.js') }}"></script>

	<!-- Feather JS -->
	<script src="{{ url('build/js/feather.min.js') }}"></script>

	<!-- Aos -->
	<script src="{{ url('build/plugins/aos/aos.js') }}"></script>

	<!-- counterup JS -->
	<script src="{{ url('build/js/jquery.waypoints.js') }}"></script>
	<script src="{{ url('build/js/jquery.counterup.min.js') }}"></script>

	<!-- Owl Carousel JS -->
	<script src="{{ url('build/js/owl.carousel.min.js') }}"></script>

	<!-- Custom JS -->
	<script src="{{ url('build/js/landing-script.js') }}"></script>

	<!-- Newsletter AJAX -->
	<script>
	$(function() {
		$('#newsletter-form').on('submit', function(e) {
			e.preventDefault();
			var $form = $(this), $btn = $('#newsletter-btn'), $msg = $('#newsletter-msg');
			$btn.prop('disabled', true).text('...');
			$msg.hide();
			$.ajax({
				url: $form.attr('action'),
				method: 'POST',
				data: $form.serialize(),
				dataType: 'json',
				success: function(res) {
					$msg.removeClass('text-danger').addClass('text-success').text(res.message).show();
					$form.find('input[name="email"]').val('');
				},
				error: function(xhr) {
					var msg = 'Une erreur est survenue.';
					if (xhr.responseJSON && xhr.responseJSON.errors && xhr.responseJSON.errors.email) {
						msg = xhr.responseJSON.errors.email[0];
					} else if (xhr.responseJSON && xhr.responseJSON.message) {
						msg = xhr.responseJSON.message;
					}
					$msg.removeClass('text-success').addClass('text-danger').text(msg).show();
				},
				complete: function() {
					$btn.prop('disabled', false).text("{{ __("S'abonner") }}");
				}
			});
		});
	});
	</script>

	@stack('scripts')
</body>
</html>
